Linaro/android-report

- deploy.sh
- doc/postgres.txt
- lkft/views.py
including:
1. command example on using psql command to run with and conditions
2. installation of django-debug-toolbar for debugging purpose.(not including changes on settings yet)
3. using bulk api to create TestCase objects for benchmark test cases
4. update to get all the benchmark results for one build at one time which would take about 10 seconds on android.l.o
> Some changes on investigation and workaround for the benchmark pages list problem

- kernelreport.sh
- lkft/lkft_config.py
- lkft/management/commands/kernelreport.py
- lkft/templates/lkft-jobs.html
- lkft/views.py
but there is still problem to show correctly for the eap build, will fix that next
> Changes to show the android-version and vts-version on the jobs page and in the output of kernelreport

- lkft/management/commands/kernelreport.py
- lkft/templates/lkft-jobs.html
- lkft/views.py
> lkft: update show build fingerprint when available

- lkft/views.py
- requirements.txt
including adding the requirements.txt file, support of the fetch_latest parameter for the download_attachments_save_result function, and check for the ci_build field.
> some trival improvements

- deploy.sh
This series of patches streamlines the deployment with less human intervention, which is ideal for automated setups.
> A couple of deploy fixes and improvements

- deploy.sh
so that we could cause the deploy.sh and then call the kernelreport.sh to generate the kernel report automatically
> More changes on the deploy.sh to prepare for calling the kernelreport.sh

- deploy.sh
and install the curl command as well
> deploy.sh: move installation of system packges early

- lkft/management/commands/kernelreport.py
> kernelreport.py: add more tuxsuite builds

- kernelreport.sh
- lkft/management/commands/kernelreport.py
which is for the issue here:
https://github.com/Linaro/android-report/issues/21
> some improvements on kernel-report and support for --no-check-kernel-version

- lkft/management/commands/kernelreport.py
was hikey when copy from other projects
> kernelreport.py: fix the hardware value for the hikey960 projects

- deploy.sh
instead of the one under liuyq account
Signedoff-by: Yongqin Liu <yongqin.liu@linaro.org>
> deploy.sh: update to clone from Linaro account

- lkft/management/commands/kernelreport.py
The testcase number is not correct as there is one vts job not calculated,
and update the report to show job links for developers to check when regressions reported
> Fix the testcase number incorrect problem and the show jobs information when regressions reported

- lcr/settings.py
- lcr/urls.py
when the DEBUG is true, for debug purpose
> add support for debug_toolbar

- deploy.sh
so that it won't wait for the interactive input
Signedoff-by: Yongqin Liu <yongqin.liu@linaro.org>
> deploy.sh: add -y option for the installation of sudo

- deploy.sh
in case it's not installed by default
> deploy.sh: install wget package

- lkft/views.py
based on the job name definition format like the following:
lkft-android-{{KERNEL_BRANCH}}-{{BUILD_NUMBER}}-cts-lkft
https://git.linaro.org/ci/job/configs.git/tree/lkft/lava-job-definitions/common/template-cts-lkft.yaml#n3
and assuming that there is no "-(\d+)-" pattern in the kernel branch name
so that we could reduce the noise caused by the build number
when the ci build was resubmitted
> lkft/views.py: get_classified_jobs: improve on the duplicated job check

- lkft/management/commands/kernelreport.py
so that we would know which job failed to run successfully
from the report, don't need to check the qa-report projects anymore
> kernelreport.py: show jobs information when not all jobs finished

- lkft/management/commands/kernelreport.py
for the card here:
https://linaro.atlassian.net/browse/LKQ-451
> kernelreport.py: stop the report for android-mainline gitlab projects

- kernelreport.sh
- lkft/management/commands/kernelreport.py
which would be easy for us to know the problem why there is no valid build
> kernelreport: add some links for invalid builds check

- kernelreport.sh
- lkft/management/commands/kernelreport.py
and change to not show the commands in the report
> kernelreport: list error projects at the very top

- lkft/management/commands/kernelreport.py
> kernelreport.py: add support for the full cts vts jobs

- lkft/management/commands/kernelreport.py
- lkft/views.py
as requested by Daniel, he removes that manually everytime
> remove the prefix spaces before the submary lines

- lkft/management/commands/kernelreport.py
so that it would be easy for scripts to check the status
> kernelreport.py: print "NOTE: project" for problem projects

- lkft/templates/lkft-gitlab-project-pipelines.html
- lkft/views.py
> lkft: support show pipelines for lkft-android-build-private project

- lkft/views.py
to help check on the pipelines
> lkft/views.py: add support to list pipelines for lkft-android-build

- lcr/qa_report.py
not report crash for gitlab build url for now
> lcr/qa_report.py: first support for the gitlab setup

- doc/postgres.txt
so that we could refer to in the future
> doc/postgres.txt: some instructions on move database

- lkft/management/commands/kernelreport.py
- lkft/views.py
so that when we resubmit the build for the older versions
for some cases, we still could get the report as expected.
> kernelreport.py: sort build versions with the kernel version

- lcr/qa_report.py
- lkft/templates/lkft-gitlab-project-pipelines.html
- lkft/views.py
so that we would know how long it is from the point
it's started
> gitlab pipeline: show create at time as well

- lkft/views.py
so that we could specify the numbers we want to show on the page
> gitlab/pipelines: add support for per_page from url

- lcr/qa_report.py
so that no need to call the apis many times
> qa_report.py: add support to pass limit for squad apis

- lkft/reportconfig.py
as there is no hikey960 available in lab now
> reportconfig.py: drop report for all the hikey960 projects

- lcr/qa_report.py
- lkft/templates/lkft-jobs.html
- lkft/urls.py
- lkft/views.py
to make it convenient for investigation.
> lkft: show trigger pipeline and lava log links

- deploy.sh
> deploy.sh: add instructions on how to install pyyaml

- deploy.sh
- lcr/qa_report.py
- lkft/templates/lkft-job-resubmit-manual.html
- lkft/templates/lkft-jobs.html
- lkft/urls.py
- lkft/views.py
So that we could adjust few lines to have the job and the build work
without resubmitting the builds and jobs
> lkft: Add support for manual resubmission of job

- kernelreport.sh
- lkft/management/commands/kernelreport.py
so that we could get report for the specified project only
> kernelreport: add support to specify qareports project

- lkft/templates/lkft-jobs.html
- lkft/views.py
so that we would have background on how to
adjust the modules
> lkft: show job duration for check

- lkft/management/commands/list-jenkins-builds.py
currently only get information on the weeks and branches
> list-jenkins-builds.py: script to get the jenkins build statistics

- kernelreport.sh
- lkft/management/commands/kernelreport.py
to prepare for the sending the report automatically
> kernelreport: support to trim lines for huge regressions

- lcr/qa_report.py
- lkft/templates/lkft-jobs-resubmitted-manually.html
- lkft/views.py
to make the GUI clear and avoid confusion
> lkft-gui: some small improvement

- lkft/views.py
> manually resubmitted jobs: list the latest jobs

- lkft/views.py
to avoid exception on the end_time
> lkft: list job, add check for the Scheduled status

- lkft/views.py
so that we could see the trend data for more older builds
> list_build: support to specify per_page parameter

- lkft/lkft_config.py
to get the correct Android version for Android12/Android13
> lkft_config.py: update for get_version_from_pname

- lkft/lkft_config.py
> lkft_config.py: set all Android11 builds to ANDROID-11

- lkft/templates/lkft-jobs.html
- lkft/views.py
to understand if some device has any problem
from the jobs list
> lkft: show device for jobs

- lcr/qa_report.py
- lkft/templates/lkft-jobs.html
- lkft/views.py
Like when the lava instance is down
> lkft: add support for jobs not submitted cases

- lkft/lkft_config.py
with correct Android versions configured
> lkft_config: add support for Android14

- lkft/views.py
which should be only reported during the development stage
> lkft: deal with corner case on cts/vts version generation

- lkft/urls.py
- lkft/views.py
to get the raw lava log content
> lkft: add page for lava log

- lkft/views.py
to avoid taking too much time to display by default
> support for fetch_latest for the pipelines pages

- lcr/urls.py
- lkft/templates/lkft-describe.html
- lkft/templates/lkft-gitlab-project-pipelines.html
- lkft/views.py
like add support of fetch_latest on the pipeline page
and the failures and jobs tables in the describe page to be togglable
> More improvements on the pipeline and describe pages

- deploy.sh
- lcr/accountviews.py
- lcr/settings.py
- lcr/urls.py
- lkft/models.py
- lkft/templates/lkft-jobs.html
- lkft/templates/lkft-projects.html
- lkft/urls.py
- requirements.txt
which needs the following changes
> upgrade to django version 4.2.8

- lcr/settings.py
- lcr/utils.py
- lkft/views.py
- requirements.txt
> lkft: more fix for version upgrade

- lkft/templates/lkft-describe.html
- lkft/templates/lkft-projects-matrix.html
- lkft/urls.py
- lkft/views.py
so that it's possible to complare from various perspactives
> improvements on matrix and aosp build history pages support

- lkft/views.py
according to the squad build id,
so that it's the same order as listed everywhere
> sort build version for the history page

- lcr/qa_report.py
- lkft/templates/lkft-describe.html
- lkft/views.py
so that it could help us to check what changes are there between the two builds.
> lkft: show first parents for the describe and previous

- lcr/qa_report.py
> qa_report.py: skip the check of first parents for 4.X kernels

- lkft/templates/lkft-describe.html
- lkft/views.py
Only google kernel/common first parents are supported, and only the jobs has been run are supported.
In the future, non first parents commits and cts/vts module level bisecting will be considered
> lkft: add draft version support for kernel bisecting

- lcr/utils.py
- lkft/views.py
for some sites like the squad,
it need to use token to download files to avoid
anonymous limit.
> utils: add support to download with token

- lkft/views.py
with the SQUAD_URL being updated to the new squad project
> lkft: update bisect to support squad url

- lkft/views.py
as the auth-token method not work always
> lkft: update to use Authorization header for SQUAD

- lcr/qa_report.py
- lkft/views.py
so that to be convenient for boottime investigation
> lkft: add boottime in describe page for bisect purpose

- lkft/views.py
in the describe page, for the convenience of boottime bisection
> lkft: list jobs for boottime projects and jobs by default

- lkft/templates/lkft-describe.html
instead of True to avoid confusion
> lkft-describe.html: show failures as failed

- lkft/templates/lkft-describe.html
as Ben suggested in https://github.com/Linaro/android-report/pull/146#pullrequestreview-1985789506
> lkft-describe.html: show as Fail insteand of failed

- lkft/views.py
instead of being sorted in alphabet order
> lkft: update matrix page to show latest versions first

- lkft/views.py
priority should be integer instead of string,
and need to specify --break-system-packages
to reinstall the tuxsuite command
> lkft/views.py: fix job defintion for bisect feature

- lkft/views.py
to get the correct jobs number of the build
based on the environment provided
> lkft/views.py: support environment for projects

- lkft/views.py
for the convenience of the resubmission
> lkft/views.py: set default reason and priority for resubmission

- lkft/lkft_config.py
- lkft/views.py
just a PoC implementation at the moment
> lkft: add support for the kunit test

- lkft/templates/lkft-describe.html
- lkft/templates/lkft-kernelchanges.html
- lkft/views.py
after the projects moved to Android-Testing namespace
> lkft: update gitlab build url
