Linaro/android-report

lcr/utils.py
lkft/views.py

This is temporary solution, will change to use the value from build metadata which is generated by the ci build scripts

some changes on how to show the cts/vts version for EAP builds

---

lkft/views.py

need to check if the return of find is >= 0,
otherwise the the return value of find would be treated as true.
Change-Id: I60e0472b305cbde9dea71e6108516932790a1d19

lkft: fix the CTS/VTS version not correct problem

---

lkft/models.py

which helps for the benchmark results display page.
And there are other potential tricks on index we could check next:
https://docs.djangoproject.com/en/3.2/ref/models/options/#indexes
Need to keep an eye on the performance when the database gets huge
in the future.

lkft: enable db_index for TestCase and TestSuite modules

---

lkft/management/commands/kernelreport.py

Add android13 projects, and differentiate between Android12 and Android13 kernels
Signed-off-by: Sumit Semwal <sumit.semwal@linaro.org>

kernelreport: add android13 projects as targets

---

lkft/templates/lkft-jobs.html
lkft/views.py

only show them when they are available, and show them with the build fingerprint for the EAP builds

update for cts vts version display

---

lkft/templates/lkft-jobs.html
lkft/views.py

problem on the use of {}.get('key', 'default')

Fix the problem when build fingerprint is no there yet

---

lkft/management/commands/kernelreport.py

which could compare the version based on the rc versions

kernelreport: add support for the android-mainline builds

---

lkft/management/commands/kernelreport.py
lkft/views.py

so that don't need to spend time on the test numbers check
for builds that unnecessary

kernelreport.py: move the check of build version earlier

---

kernelreport.sh
lkft/management/commands/kernelreport.py

but different commit ids.
Also change the way how the exact kernel version specified.
need to specify it with the --exact-version-1 option now.
Please run like this:
./kernelreport.sh kernel_ver [--exact-version-1 exact_ver1 [--exact-version-2 exact_ver2 [--reverse-build-order]]] [--no-check-kernel-version]
This change is for the issue reported here:
https://github.com/Linaro/android-report/issues/31

kernelreport.sh: add support for two builds with the same kernel version

---

lkft/management/commands/kernelreport.py

should the results for db845c and hikey960 first

kernelreport.py: adjust the order for android-mainine reports

---

lkft/management/commands/kernelreport.py
lkft/views.py

change to use the number of finished successfully job help to check,
if the number of the finished successfully jobs is the same as the number of all jobs,
then that means  the all the jobs are finished successfully, and should be able to be used for comparison

Fix the problem to fail to get report for x15 builds

---

deploy.sh

for the case, the sudo command is not installed by default,
but it will be run with the root user by default,
especially for some docker container cases

deploy.sh: install sudo package when it's not installed by default

---

lkft/management/commands/kernelreport.py

also update the branch name for some projects,
where were not clear.
The newly added projects are the followings:
- '4.14-stable-android11-hikey960-lkft',
- '4.19-stable-master-hikey960-lkft',
- '4.19-stable-master-hikey-lkft',
- '4.19-stable-android11-hikey960-lkft',
- '5.4-gki-android11-aosp-master-db845c',
- '5.4-gki-android11-aosp-master-hikey960',
- '5.4-lts-gki-android12-private-android12-db845c',
- '5.4-lts-gki-android12-private-android12-hikey960',
- '5.4-gki-android11-private-android12-db845c',
- '5.4-gki-android11-private-android12-hikey960',

kernelreport.py: add more projects to be reported

---

lkft/management/commands/kernelreport.py

Since we're sending separate reports on many 5.x kernels, separate them out
and make it clearer on what kernel-userspace combos are reported together.
Signed-off-by: Sumit Semwal <sumit.semwal@linaro.org>

kernelreport.py: Group the kernel_ver according to reports

---

lkft/management/commands/kernelreport.py

as the kernels branches have been deprecated

kernelreport.py: drop the 4.4-o and 4.9-o projects

---

lkft/management/commands/kernelreport.py

to report for the 4.14-stable + android12 project

kernelreport: add 4.14-stable-android12-hikey960-lkft

---

lkft/management/commands/kernelreport.py

only for db845c build at the moment.
there are problem to build the hikey960 kernel
with the android13-5.15 branch at the moment

kernelreport.py: add support for android13-5.15 kernel

---

lcr/qa_report.py
lkft/management/commands/kernelreport.py

which is the sum of all the combos,
also add the support for the regressions number and
antiregressions number

kernelreport.py: show summary number at the top

---

lkft/management/commands/kernelreport.py

as one project of the android12-5.4 kernels

lkft: add support for the db845c android11 + android12-5.4 project

---

kernelreport.sh

For some cases, we Would copy the kernel version information
from webpage or somewhere, which could contain one or more
leading or trailing spaces that we are not aware of, and
it would cause the command failed to parse.
Here we use the sed command to delete all the leading and trailing spaces,
to support such cases

kernelreport.sh: strip the leading or trailing space for parameters

---

lkft/management/commands/kernelreport.py

We have the db845c report printed first for some kernels,
and have the hikey960 report printed first others,
here update to print the db845c report before the hikey960 report
for all the kernels to avoid potential confusions when read the report.
and the following kernels would be affected by this change:
android11-5.4-lts
android11-5.4
EAP-android12-5.10-lts

kernelreport.py: print the report for db845c before hikey960

---

lkft/management/commands/kernelreport.py

kernelreport.py: add report for the 4.19q/4.14q/4.9q kernels

---

lkft/management/commands/kernelreport.py

sometimes we might submit some jobs but the cts and vts job
to test some platform, to avoid confusion, here use
the modules_total value for the check

kernelreport.py: deal with no cts vts jobs case

---

lkft/management/commands/kernelreport.py

to support the automatical support based on the kernel branch,
also remove the configs for the tuxsuite builds

kernelreport.py: add branch entries for 4.X kernels

---

lkft/management/commands/kernelreport.py

as they would have different build versions from two different repositories

kernelreport.py: remove 4.19-stable-aosp-x15 from android-hikey-linaro-4.19-stable-lkft

---

lkft/views.py

when the job result is cached already

lkft/views.py: do not regenerate the testcases information

---

lkft/views.py

as the official release does not have the rc number,
so we set the rc for the release to 65536 which
should not be possible for the rc number,
so that the official release will be list first before
the rc builds, and the rc build could be listed in order as well.
For stable builds that do not have rc numbers,
they will be sorted by the kernel version and the time when it's created

lkft/views.py: fix the sort problem on rc number

---

lkft/management/commands/kernelreport.py

as they are stopped since February

kernelreport.py: drop the report for the -p branches

---

lkft/reportconfig.py

This is a temporary measure, while the 4.x reports are completed.

reportconfig: Bring back 4.4, 4.9, 4.14, 4.19

---

lkft/reportconfig.py

as there is not enough hikey960 devices there now

reportconfig.py: drop the full cts vts projects

---

lkft/management/commands/kernelreport.py

the wrong variables was used and that made it print
the same list as the normal failures.
changed to use the variable passed to the function with
a new variant name

kernelreport.py: fix problem for assumption failure list

---

lkft/reportconfig.py

including:
4.9q-android12gsi-hikey960
4.14q-android12gsi-hikey960
4.14-stable-android12-hikey960-lkft-public
4.19q-android12gsi-hikey960
5.4-gki-android11-android12-hikey960
5.4-gki-android12-android12-hikey960
5.4-lts-gki-android12-android12-hikey960
5.10-gki-android12-android12-hikey960
5.10-lts-gki-android12-android12-hikey960
5.4-gki-android11-android12-db845c
5.4-gki-android12-android12-db845c
5.4-lts-gki-android12-android12-db845c
5.10-gki-android12-android12-db845c
5.10-lts-gki-android12-android12-db845c
5.4-gki-android12-android12-db845c-presubmit
5.10-gki-android12-android12-db845c-presubmit
5.10-gki-android12-android12-db845c-full-cts-vts

reportconfig.py: add support for public android12 projects

---

lkft/reportconfig.py

This reverts commit e1a376ff821c5de975a97c2db6ebd3e4e5647d32.
As there are 3 hikey960 deployed on v.l.o now

Revert "reportconfig.py: drop report for all the hikey960 projects"

---

deploy.sh

to fix the error reported like this:
```
File "/android/django_instances/android-report/lkft/urls.py", line 3, in <module>
from . import views
File "/android/django_instances/android-report/lkft/views.py", line 37, in <module>
from lcr import qa_report, bugzilla
File "/android/django_instances/android-report/lcr/qa_report.py", line 13, in <module>
from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
```

deploy.sh: install ruamel.yaml module

---

deploy.sh
requirements.txt

instead of running the pip install command separately

lkft: move installation for ruamel.yaml to requirements.txt

---

lkft/reportconfig.py

only for the db845c aosp master project for now

reportconfig.py: add report for android14-5.15 kernel

---

lcr/qa_report.py

for the problem like reported here:
File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
(data_string, format))
ValueError: time data '2023-01-15T20:40:15Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

lcr/qa_report.py: fix datetime format parsing error

---

lkft/lkft_config.py

so that bugs could be created successfully

lkft_config.py: set hardware name for RB5

---

lkft/views.py

for the case like this:
https://bugs.linaro.org/show_bug.cgi?id=6011
where two projects has reported the problem,
but could not specify two platfroms there.
so this is a workaround for the problem.

lkft/views.py: drop platform for bug search

---

lcr/qa_report.py
lkft/templates/lkft-describe.html
lkft/templates/lkft-gitlab-project-pipelines.html
lkft/templates/lkft-kernelchanges.html
lkft/templates/lkft-projects-matrix.html
lkft/urls.py
lkft/views.py
static/report/css/compatibility_result.css

Still in progress, the changes here are the initial part part to improve the triage work.
Future improvements will be done after being used for a while. The features enabled here including:
1. matrix page: help to see what projects are setup now
2. describe pages linked to the pipeline pages to avoid finding projects one by one from various places and enabled fetch latest future as well, which could be called from the gitlab side, to improve the slowness problem

Some improvements for triage work

---

lkft/templates/lkft-gitlab-project-pipelines.html
lkft/views.py

The report file is not necessary, and this googlesource link will be convenient for triage

lkft: point to the googlesource log link on the pipeline page

---

lcr/utils.py

to avoid the cases the there are spaces in the header

lcr/utils.py: quote the header paramter for download

---

lkft/views.py

by dropping the 320+ chars of the testcase name.
The are prefix and suffix like 0_default_primary_0 could be used to identify the test cases.
The following are some of the long name test cases for reference:
InputStreamInvalidConfig/StreamOpenTest#OpenInputOrOutputStreamTest/0_default_primary_0__8000_random_string_______deviceType____AUDIO_DEVICE_IN_DEFAULT____address_____id___________tracks____2____source____AUDIO_SOURCE_DEFAULT____gain___1_000000___destination_____unspecified_________channelMask________tags____0________source____AUDIO_SOURCE_DEFAULT____gain___1_000000___destination_____device_____deviceType____AUDIO_DEVICE_OUT_DEFAULT____address_____id___________channelMask________tags____0______
InputStreamInvalidConfig/StreamOpenTest#OpenInputOrOutputStreamTest/1_default_primary_1__800 …

lkft/views.py: workaround for too long testcase name issue

---

lkft/views.py

set the priority as 60 with hardcoded value,
and install tuxsuite with --break-system-packages specified
The bisection function needs to be reimplemented with tuxsuite plan finally as discussed with Vishal, for now it's just an experiment for the concept

bisection: workarounds for priority and tuxsuite installation

---

lkft/views.py

when the same commit was triggered by multiple builds

lkft/views.py: use the last gitlab url

---

lcr/qa_report.py

instead of the lava log url directly

lcr/qa_report.py: using REST Api to get lava log

---

lkft/views.py

to avoid wrong job number information.

lkft/views.py: ignore environment for build numbers

---

lkft/templates/lkft-projects-matrix.html
lkft/views.py

410c140ca747 lkft/views.py: list all the build versions
fac1c4a37b5d lkft-projects-matrix.html: show total failed numbers always

two improvements on the display of the failures and matrix

---

lkft/views.py

to avoid crash when there was issues with the first build for some reasons

lkft: iterate all builds to find pipeline.trigger.url
